framework:
    workflows:
        work_day:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'single_state'
                arguments:
                - 'state'
            supports:
                - App\Entity\WorkDay
            initial_place: instantiated
            places:
                - instantiated
                - to_complete
                - completed
                - unvalidated
                - validated
                - flagged
                - edition
            transitions:
                add_basic_infos:
                    from:
                        - instantiated
                        - edition
                    to:   to_complete
                add_completed_tasks:
                    from: to_complete
                    to:   completed
                submit_admin:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: completed
                    to:   validated
                submit:
                    guard: "is_granted('ROLE_WORKER')"
                    from: completed
                    to:   unvalidated
                validate:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: unvalidated
                    to:   validated
                flag:
                    guard: "is_granted('ROLE_WORKER')"
                    from: validated
                    to:   flagged
                modify:
                    from:
                        - to_complete
                        - completed
                        - unvalidated
                    to:   edition
                modify_admin:
                    guard: "is_granted('ROLE_ADMIN')"
                    from:
                        - to_complete
                        - completed
                        - unvalidated
                        - validated
                        - flagged
                    to:   edition
                ignore:
                    guard: "is_granted('ROLE_ADMIN')"
                    from: flagged
                    to:   validated

